<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>KerolosBot_Logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="KerolosBot_Logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="bin\Debug\net10.0-windows\" />
  </ItemGroup>

</Project>